### ISSUE TITLE
Limit length of Barcode 

### ISSUE THREAD

**Issue by g438** [nordpos/nordpos#18]
Hello and congratulations for your work, i tried NordPos on Windows and Linux with MySQL, it works perfectly! I'm going to finish the complete translation in Italian and send you maximum in two days.
I need to limit the field Barcode to 11-digit, if i do it from mysql (field CODETYPE) i get an error and i can not enter the product, how could i do it directly from the program? Thank You

**Comment by svininykh** [comment]
Hi, I am glad to see translation in Italian for my project. Can you send example of your barcode. The CODETYPE field not included and not used in business logic of application. Do you need enter 11-digit only, or you need generate 11-digit barcode also?

**Comment by g438** [comment]
I solved by configuring the reader. By tomorrow i'll send you the translation files. Great job, missing only a few reports and some documentation. Greetings
