### ISSUE TITLE
Steps or what imports are necessary to add a new JPanel?

### ISSUE THREAD

**Issue by icebergdelphi** [nordpos/nordpos#21]
Hi again, we are trying to add a new module or new Jpanel inside a System-->Configuration TabPanel,
i mean, we need a CFDI Module ( Invoices Digital Internet, or  Electronic Invoice for México),
We found  JPanelConfiguration.Java, but when we run the app a warning or error appears:
com.openbravo.pos.forms.BeanFactoryException: java.lang.reflect.InvocationTargetException.

We are thinking that something is missing, so what  are the imports or   necessary code to add a new Jpanel? for correct working Thank you.

Code from JPanelConfiguration.Java
public JPanelConfiguration(AppProperties props) {
        
        config = new AppConfig(props.getConfigFile());
        
        initComponents();
        
        // Inicio lista de paneles
        m_panelconfig = new ArrayList<>();
        m_panelconfig.add(new JPanelConfigGeneral());
        m_panelconfig.add(new JPanelConfigDatabase());
        m_panelconfig.add(new JPanelConfigHardware());        
        m_panelconfig.add(new JPanelConfigLocale());
        m_panelconfig.add(new JPanelConfigPayment(props));
        m_panelconfig.add(new JPanelConfigServer());
        m_panelconfig.add(new JPanelConfigCfdi()); /* NEW MODULE FOR MEXICO*/
        
        // paneles auxiliares
        for (PanelConfig c: m_panelconfig) {
            m_jConfigOptions.addTab(c.getPanelConfigName(), c.getConfigComponent());
        }
    }

**Comment by svininykh** [comment]
So sorry I did not have answer without `JPanelConfigCfdi` class source code. But I can recommend check class declaration. It's extends `JPanel` and implements `PanelConfig`:
```java

public class JPanelConfigServer extends javax.swing.JPanel implements PanelConfig {

}
```
