### ISSUE TITLE
New Customer creation panel doesn't show some fields 

### ISSUE THREAD

**Issue by naqvisat** [nordpos/nordpos#23]
During creation of new customer I found out that in the contact tab some fields donot appear properly. 

For example in the below snapshot you can see that there are some fields below Eamil but they are not visible.

![customer_panel_view_issue](https://cloud.githubusercontent.com/assets/6160061/6411477/423181ec-be79-11e4-895b-edae067ffb33.jpg)

**Comment by naqvisat** [comment]
How can I assign myself to this issue?

**Comment by svininykh** [comment]
You can open configuration panel and change font size.
