### ISSUE TITLE
New Customer creation panel doesn't indicate mandatory fields

### ISSUE THREAD

**Issue by naqvisat** [nordpos/nordpos#24]
On Customer creation panel, fields should be marked with (*) to indicate if they are necessary to create Customer.

![customer_panel_view_issue](https://cloud.githubusercontent.com/assets/6160061/6413669/387ac064-be92-11e4-9760-61a5728c2d0c.jpg)

**Comment by naqvisat** [comment]
This can be considered enhancement.

**Comment by svininykh** [comment]
You can see patch. Now all mandatory fields set yellow background.
![screenshot-nord pos - 3 1 0ce-2](https://cloud.githubusercontent.com/assets/1005780/16362516/87036e02-3bd2-11e6-9ed1-c60eebf103df.png)

**Comment by dixon22ma** [comment]
Hello, this change applies only when creating a new record. If you create a customer, you fill your mandatory fields (yellow) then modified such changes leaving him in a null value can save the record.
