### ISSUE TITLE
No confirmation after saving the new Customer

### ISSUE THREAD

**Issue by naqvisat** [nordpos/nordpos#25]
After I create a new Customer and click save... I don't see any confirmation indicating whether customer was successfully inserted or not! 

![customer_panel_view_issue - copy](https://cloud.githubusercontent.com/assets/6160061/6413759/d16ac3aa-be92-11e4-9e9a-746d379731a4.jpg)

**Comment by svininykh** [comment]
After press save button counter of table fields increase. This is not bug.
