### ISSUE TITLE
Some good Ideas to add

### ISSUE THREAD

**Issue by icebergdelphi** [nordpos/nordpos#26]
Hi, i give you a link to download a OpenBravo POS Modified Software in Mexico, you could see and take good idea from it .

iTPV-18E

http://www.4shared.com/rar/ZwcjnUMsba/iTPV-18E.html

**Comment by svininykh** [comment]
I know about iTPV fork of Openbravo POS. But you don't have source code. If you need any features, you can create issues or post on http://sourceforge.net/p/nordpos/discussion/nordpos/ about what do you need.
