### ISSUE TITLE
нужна доработка функционала

### ISSUE THREAD

**Issue by remaks** [nordpos/nordpos#32]
имеется хотелка:

1. оформляется заказ, на фронте печатает принтер марку для клиента с номером заказа.
Марка выдается клиенту
2. на кухне печатается что нужно сделать по этому номеру заказа.
3. когда заказ готов, и с кухни принесен, на фронте фиксируется готовность заказа.
4. информация о готовности заказа отображена на "большом экране" *
  * большой экран = это "типа ТВ/большой монитор" с веб браузером, на котором хорошо видно: готовые номера заказов - список.
5. как только клиент забрал заказ, выксируется выдача заказа на фронте.

---
фронт - терминал, на котором работает официанты

**Comment by svininykh** [comment]
1. Без изменения кода можно использовать встроенный механизм скриптов http://wiki.openbravo.com/wiki/Openbravo_POS_Scripting_Tutorial
2. Можно сделать также скрипт и шаблон для заказа отправляемого на второй кухонный принтер. В шаблоне чека нужно указать: `<ticket printer="2">`.
3, 4 и 5 лучше развивать в отдельном мобильном интерфейсе на базе сервлета https://github.com/nordpos-mobi/restaurant-service
