### ISSUE TITLE
Не печатаются чеки.

### ISSUE THREAD

**Issue by ghost** [nordpos/nordpos#35]
Не печатаются чеки. При нажатии на кнопку печати чека ничего не происходит. Если в настройках указать screen, то чек отображается на экране.

Настройки принтера выставил такие:
![1](https://cloud.githubusercontent.com/assets/7967243/13549988/03025fe8-e33d-11e5-96e6-2aa9a6c96677.png)

Отчеты печатаются нормально.

**Comment by svininykh** [comment]
Спасибо. Есть такая ошибка, ещё в том году пользователь заметил https://github.com/nordpos/nordpos/issues/29 Но только сегодня у меня появилось её закрыть. Можете самостоятельно пересобрать код или дождаться ближайшего релиза.
